name: Application Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test-utils:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Install Dependencies
        run: npm ci

      - name: Utils Test
        run: npm t utils